# Generated by Django 5.1.6 on 2025-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collector", "0002_auto_20160522_0632"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="visit_count",
        ),
        migrations.AlterField(
            model_name="log",
            name="content_id",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="log",
            name="user_id",
            field=models.CharField(max_length=16),
        ),
    ]
